baseURL = 'https://arvela.pt/'
languageCode = 'en-us'
theme        = "github.com/halogenica/beautifulhugo"
title = 'Sofia Arvela'

[Params]
  logo       = "img/profile.jpg"
  subtitle   = "DevOps Engineer"
  dateformat = "2 Jan, 2006"
  commit = false
  rss = true

  [Params.author]
    name = "Sofia Arvela"
    github   = "ThisIsFroggie"
    linkedIn = "SofiaArvela"
    medium   = "SofiaArvela"

[[module.imports]]
  path = "github.com/halogenica/beautifulhugo"

[[menu.main]]
name    = "Home"
url     = "/"
weight  = 1

[[menu.main]]
name = "Blog"
url  = "/posts/"
weight = 20

[[menu.main]]
name    = "Resume (PDF)"
url     = "/assets/sofia-arvela-cv.pdf"
weight  = 100
